### ISSUE TITLE
As a player I want limited darts to throw so that the game has challenge

### ISSUE THREAD

**Issue by koktavy** [nyu-software-engineering/ar-mini-games#100]
As a player I want limited darts to throw so that the game is challenging.

## Estimate of work
* L

## Acceptance criteria
- [x] #105 Implement counter UI (3 darts in corner of screen, etc.)
- [x] #106 Script counter to keep track of darts thrown
- [x] #107 Prompt a restart screen once all darts are thrown, including the round's score

- [x] Must pass automated tests
- [x] Must be code reviewed
- [x] Must be checked into the master branch via pull request
