### ISSUE TITLE
As a user I want to play multiplayer so that I can enjoy this game with friends

### ISSUE THREAD

**Issue by koktavy** [nyu-software-engineering/ar-mini-games#128]
As a user I want to play multiplayer so that I can enjoy this game with friends.

## Estimate of work
* XXL

## Acceptance criteria
- [ ] #129 Use Cloud Anchors to enable multiplayer
- [ ] #130 Users can join the same game
- [ ] #131 Users can see the same board
- [ ] #132 Users can see each other's scores
- [ ] #133 Game declares winner based on score
- [ ] Must pass automated tests
- [ ] Must be code reviewed, and checked for functionality by the team
- [ ] Must be checked into the master branch via pull request
