### ISSUE TITLE
As a developer, I want to learn ARCore to make augmented reality projects. - Antony

### ISSUE THREAD

**Issue by asunwoo98** [nyu-software-engineering/ar-mini-games#21]
As a developer, I want to learn ARCore to make augmented reality projects.

## Estimate of work
* L

## Acceptance Criteria
* [x] #50 Install ARCore to Unity
* [x] #53 Download ARCore Cloud Anchors
* [x] #56 Build Demo Scene to your mobile device
