### ISSUE TITLE
As a user I want to tap the screen to throw a dart so that gameplay progresses.

### ISSUE THREAD

**Issue by charleswdickstein** [nyu-software-engineering/ar-mini-games#3]
As a user I want to tap the screen to throw a dart so that gameplay progresses.

## Estimate of Work 
* L 

## Acceptance Criteria 
* [x] #63 Dart appears statically in environment in the middle of the screen 
* [x] #65 Dart angle corresponds to angle of camera position
* [ ] #64 Magnitude of dart corresponds with screen swipe
