### ISSUE TITLE
As a developer, I want to learn ARCore to make augmented reality projects. - Tavius

### ISSUE THREAD

**Issue by koktavy** [nyu-software-engineering/ar-mini-games#32]
As a developer, I want to learn ARCore to make augmented reality projects.

## Estimate of work
* L

## Acceptance Criteria
* [x] #52 Install ARCore to Unity
* [x] #55 Download ARCore Cloud Anchors
* [x] #58 Build Demo Scene to your mobile device
