### ISSUE TITLE
As a developer, I want to learn ARCore to make augmented reality projects. - Charlie

### ISSUE THREAD

**Issue by koktavy** [nyu-software-engineering/ar-mini-games#33]
As a developer, I want to learn ARCore to make augmented reality projects.

## Estimate of work
* L

## Acceptance Criteria
* [x] #51 Install ARCore to Unity
* [x] #54 Download ARCore Cloud Anchors
* [x] #57 Build Demo Scene to your mobile device
