### ISSUE TITLE
As a user I want a dartboard to throw darts to increase my score.

### ISSUE THREAD

**Issue by charleswdickstein** [nyu-software-engineering/ar-mini-games#4]
As a user I want a dartboard to throw darts to increase my score.

## Estimate of work
* L

## Acceptance criteria
* [x] #60 A Unity prefab of a dart board should be visible with colored inner circles representing scoring tiers
* [x] #61 When a dart collides with the board, the dart should stick to the board
* [x] #83 A realistic 3D model of a dart board is added to the project
