### ISSUE TITLE
As a user I want to keep score of my game so that I can track my progress.

### ISSUE THREAD

**Issue by charleswdickstein** [nyu-software-engineering/ar-mini-games#5]
As a user I want to keep score of my game so that I can track my progress.

## Estimate of Work
* L

## Acceptance Criteria
* [x] #66 Dart collisions should increase the overall score 
* [x] #76 The scoring tier that the dart collides with should be recorded to the overall score 
* [x] #68 The high score of a user should be recorded 
* [x] #67 The user should be alerted when a new high score is reached.
