### ISSUE TITLE
As an engineer I want to test scripts to ensure code coverage 

### ISSUE THREAD

**Issue by asunwoo98** [nyu-software-engineering/ar-mini-games#73]
As a programmer, I want to test scripts to ensure code coverage

## Estimate of work
* L

## Acceptance criteria
* [ ] #79 Antony has written unit tests for his code and ensured it is tested properly
* [ ] #80 Charlie has written unit tests for his code and ensured it is tested properly
* [ ] #78 Tavius has written unit tests for his code and ensured it is tested properly
