### ISSUE TITLE
As a user I want the app to use AR for an immersive experience.

### ISSUE THREAD

**Issue by koktavy** [nyu-software-engineering/ar-mini-games#88]
As a user I want the app to use AR for an immersive experience.

## Estimate of work
* XL

## Acceptance criteria
* [x] #89 Add ARCore to the project.
* [x] #90 Place the dart board in a cloud-anchored position in space.
* [x] #91 App runs on iOS.
* [x] #92 App runs on Android.
