### ISSUE TITLE
As a player I want to place the dartboard in space to play in any environment

### ISSUE THREAD

**Issue by koktavy** [nyu-software-engineering/ar-mini-games#99]
As a player I want to place the dartboard in space to play in any environment.

## Estimate of work
* XL

## Acceptance criteria
- [x] #108 Prompt to place dartboard
- [x] #109 Tap to place dartboard
- [x] #110 Minimum distance for board placement

- [x] Scripts must pass automated tests
- [x] Must be code reviewed
- [x] Must be checked into the master branch via pull request
